In [9]:
import numpy as np
import pandas as pd

In [10]:
coursera = pd.read_csv('Coursera.csv')

In [11]:
coursera.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [12]:
#Course Name
#University
#Dificulty Level
#Course Description
#Skills

In [13]:
coursera = coursera[['Course Name', 'University', 'Difficulty Level', 'Course Rating', 'Course URL', 'Course Description', 'Skills']]

In [14]:
coursera.isnull().sum()

Course Name           0
University            0
Difficulty Level      0
Course Rating         0
Course URL            0
Course Description    0
Skills                0
dtype: int64

In [15]:
coursera.duplicated().sum()

98

In [16]:
coursera.drop_duplicates()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...
...,...,...,...,...,...,...,...
3517,"Capstone: Retrieving, Processing, and Visualiz...",University of Michigan,Beginner,4.6,https://www.coursera.org/learn/python-data-vis...,"In the capstone, students will build a series ...",Databases syntax analysis web Data Visuali...
3518,Patrick Henry: Forgotten Founder,University of Virginia,Intermediate,4.9,https://www.coursera.org/learn/henry,"�Give me liberty, or give me death:� Rememberi...",retirement Causality career history of the ...
3519,Business intelligence and data analytics: Gene...,Macquarie University,Advanced,4.6,https://www.coursera.org/learn/business-intell...,�Megatrends� heavily influence today�s organis...,analytics tableau software Business Intellig...
3520,Rigid Body Dynamics,Korea Advanced Institute of Science and Techno...,Beginner,4.6,https://www.coursera.org/learn/rigid-body-dyna...,"This course teaches dynamics, one of the basic...",Angular Mechanical Design fluid mechanics F...
3521,Architecting with Google Kubernetes Engine: Pr...,Google Cloud,Intermediate,4.7,https://www.coursera.org/learn/deploying-secur...,"In this course, ""Architecting with Google Kube...",bigtable bigquery SQL Google Cloud Platform...

In [17]:
coursera.iloc[1260].Skills

'Strategy  Planning  Creativity  Entrepreneurship  thought  business plan  psychology  i-deas  Team Building  Risk business entrepreneurship'

In [18]:
def convert(string):
    li = list(string.split('  '))
    return li

In [19]:
coursera['Skills'] = coursera['Skills'].apply(convert)

In [20]:
coursera.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,"[Drama, Comedy, peering, screenwriting, film, ..."
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...","[Finance, business plan, persona (user experie..."
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,"[chemistry, physics, Solar Energy, film, lambd..."
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...","[accounts receivable, dupont analysis, analysi..."
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,"[Data Analysis, select (sql), database managem..."

In [21]:
coursera['Course Description'][1260]

'How do you implement ideas?    This course provides practical proven tools for transforming an idea into a product or service that creates value for others.  As students acquire these tools, they learn how to tell bad ideas from good, how to build a winning strategy, how to shape a unique value proposition, prepare a business plan, compare their innovation to existing solutions, build flexibility into their plan and determine when best to quit.  As a vital part of the course students conduct on-site interviews with entrepreneurs who have launched startups, and are eager to share their valuable insights with them.  Upon completing this course successfully, graduates will be able to: 1.\\tTransform ideas into real products, services and processes, by validating the idea, testing it, and turning it into a growing, profitable and sustainable business. 2.\\tIdentify the major steps and requirements in order to estimate the potential of an innovative idea as the basis of an innovative project. 3.\\tReach creative solutions via an iteration of a virtually endless stream of world-changing ideas and strategies, integrating feedback, and learning from failures along the way. 4.\\tApply the 10 entrepreneurial tools in creating a business plan for a new innovative venture. 5.\\tApply methods and strategies learned from interviews with startup entrepreneurs and innovators.  6.\\tCommunicate and sell innovative ideas successfully.'

In [22]:
coursera['Course Description'] = coursera['Course Description'].apply(lambda x:x.split())

In [23]:
coursera.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,"[Write, a, Full, Length, Feature, Film, Script...","[Drama, Comedy, peering, screenwriting, film, ..."
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"[By, the, end, of, this, guided, project,, you...","[Finance, business plan, persona (user experie..."
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,"[This, course, consists, of, a, general, prese...","[chemistry, physics, Solar Energy, film, lambd..."
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"[When, it, comes, to, numbers,, there, is, alw...","[accounts receivable, dupont analysis, analysi..."
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,"[In, this, course, you�ll, learn, how, to, eff...","[Data Analysis, select (sql), database managem..."

In [24]:
coursera['University'] = coursera['University'].apply(convert)

In [25]:
coursera.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,[Michigan State University],Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,"[Write, a, Full, Length, Feature, Film, Script...","[Drama, Comedy, peering, screenwriting, film, ..."
1,Business Strategy: Business Model Canvas Analy...,[Coursera Project Network],Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"[By, the, end, of, this, guided, project,, you...","[Finance, business plan, persona (user experie..."
2,Silicon Thin Film Solar Cells,[�cole Polytechnique],Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,"[This, course, consists, of, a, general, prese...","[chemistry, physics, Solar Energy, film, lambd..."
3,Finance for Managers,[IESE Business School],Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"[When, it, comes, to, numbers,, there, is, alw...","[accounts receivable, dupont analysis, analysi..."
4,Retrieve Data using Single-Table SQL Queries,[Coursera Project Network],Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,"[In, this, course, you�ll, learn, how, to, eff...","[Data Analysis, select (sql), database managem..."

In [26]:
coursera['University'] = coursera['University'].apply(lambda x:[i.replace(" ","") for i in x])
coursera['Skills'] = coursera['Skills'].apply(lambda x:[i.replace(" ","") for i in x])

In [27]:
coursera['tags'] = coursera['University'] + coursera['Skills'] + coursera['Course Description']

In [28]:
coursera.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,tags
0,Write A Feature Length Screenplay For Film Or ...,[MichiganStateUniversity],Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,"[Write, a, Full, Length, Feature, Film, Script...","[Drama, Comedy, peering, screenwriting, film, ...","[MichiganStateUniversity, Drama, Comedy, peeri..."
1,Business Strategy: Business Model Canvas Analy...,[CourseraProjectNetwork],Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"[By, the, end, of, this, guided, project,, you...","[Finance, businessplan, persona(userexperience...","[CourseraProjectNetwork, Finance, businessplan..."
2,Silicon Thin Film Solar Cells,[�colePolytechnique],Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,"[This, course, consists, of, a, general, prese...","[chemistry, physics, SolarEnergy, film, lambda...","[�colePolytechnique, chemistry, physics, Solar..."
3,Finance for Managers,[IESEBusinessSchool],Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"[When, it, comes, to, numbers,, there, is, alw...","[accountsreceivable, dupontanalysis, analysis,...","[IESEBusinessSchool, accountsreceivable, dupon..."
4,Retrieve Data using Single-Table SQL Queries,[CourseraProjectNetwork],Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,"[In, this, course, you�ll, learn, how, to, eff...","[DataAnalysis, select(sql), databasemanagement...","[CourseraProjectNetwork, DataAnalysis, select(..."

In [29]:
new_df = coursera[['Course Name', 'Course Rating', 'Course URL', 'tags']]

In [30]:
new_df['tags'] = new_df['tags'].apply(lambda x:' '.join(x))

C:\Users\niles\AppData\Local\Temp\ipykernel_18232\2266712157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:' '.join(x))

In [31]:
new_df.head()

,Course Name,Course Rating,Course URL,tags
0,Write A Feature Length Screenplay For Film Or ...,4.8,https://www.coursera.org/learn/write-a-feature...,MichiganStateUniversity Drama Comedy peering s...
1,Business Strategy: Business Model Canvas Analy...,4.8,https://www.coursera.org/learn/canvas-analysis...,CourseraProjectNetwork Finance businessplan pe...
2,Silicon Thin Film Solar Cells,4.1,https://www.coursera.org/learn/silicon-thin-fi...,�colePolytechnique chemistry physics SolarEner...
3,Finance for Managers,4.8,https://www.coursera.org/learn/operational-fin...,IESEBusinessSchool accountsreceivable dupontan...
4,Retrieve Data using Single-Table SQL Queries,4.6,https://www.coursera.org/learn/single-table-sq...,CourseraProjectNetwork DataAnalysis select(sql...

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\niles\AppData\Local\Temp\ipykernel_18232\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [39]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [42]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [48]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\niles\AppData\Local\Temp\ipykernel_18232\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [92]:
new_df.rename(columns = {'Course Name':'course_name'}, inplace = True)
new_df.rename(columns = {'Course Rating':'course_rating'}, inplace = True)
new_df.rename(columns = {'Course URL':'course_url'}, inplace = True)

C:\Users\niles\AppData\Local\Temp\ipykernel_18232\601824688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns = {'Course Name':'course_name'}, inplace = True)
C:\Users\niles\AppData\Local\Temp\ipykernel_18232\601824688.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns = {'Course Rating':'course_rating'}, inplace = True)
C:\Users\niles\AppData\Local\Temp\ipykernel_18232\601824688.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns = {'Course URL':'course_url'}, inplace = True)

In [100]:
new_df.head(-10)

,course_name,course_rating,course_url,tags
0,Write A Feature Length Screenplay For Film Or ...,4.8,https://www.coursera.org/learn/write-a-feature...,michiganstateuniv drama comedi peer screenwrit...
1,Business Strategy: Business Model Canvas Analy...,4.8,https://www.coursera.org/learn/canvas-analysis...,courseraprojectnetwork financ businessplan per...
2,Silicon Thin Film Solar Cells,4.1,https://www.coursera.org/learn/silicon-thin-fi...,�colepolytechniqu chemistri physic solarenergi...
3,Finance for Managers,4.8,https://www.coursera.org/learn/operational-fin...,iesebusinessschool accountsreceiv dupontanalys...
4,Retrieve Data using Single-Table SQL Queries,4.6,https://www.coursera.org/learn/single-table-sq...,courseraprojectnetwork dataanalysi select(sql)...
...,...,...,...,...
3507,Healthy Aging and the Future of Cannabis Research,4.7,https://www.coursera.org/learn/aging-research-...,universityofcoloradobould age alternativemedic...
3508,Pixel Art for Video Games,4,https://www.coursera.org/learn/pixel-art-video...,michiganstateuniv pixel zbrush art gamedesign ...
3509,Google Ads for Beginners,4.5,https://www.coursera.org/learn/google-ads-begi...,courseraprojectnetwork adverti write projectma...
3510,Esports Teams and Professional Players,4.5,https://www.coursera.org/learn/esports-teams-p...,"universityofcalifornia,irvin benefit journal c..."
3511,Visual Perception and Visual Illusions,Not Calibrated,https://www.coursera.org/learn/visualperception,saintpetersburgstateuniv gom art learnabl cogn...

In [94]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [95]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [96]:
from sklearn.metrics.pairwise import cosine_similarity

In [97]:
similarity = cosine_similarity(vectors)

In [108]:
def recommend(course):
    course_index = new_df[new_df['course_name'] == course].index[0]
    distances = similarity[course_index]
    
    course_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x:x[1])[1:11]
    
    for i in course_list:
        print(new_df.iloc[i[0]].course_name)

In [109]:
recommend('Pixel Art for Video Games')

Low Poly Art For Video Games
Introduction to Game Development
Current Gen 3D Game Prop Production
Intermediate Object-Oriented Programming for Unity Games
Business of Games and Entrepreneurship
Game Design Document: Define the Art & Concepts
World Design for Video Games
C# Programming for Unity Game Development Capstone Project
Introduction to Game Design
Modern Art & Ideas

In [102]:
import pickle

In [103]:
pickle.dump(new_df,open('coursera.pkl', 'wb'))

In [105]:
pickle.dump(similarity,open('similarity.pkl', 'wb'))